name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config --global user.email "rehcliw@gmail.com"
          git config --global user.name "rehcliw"
      - run: npm install
      - run: npm run build
      - run: npm run deploy
